 - name: Install python3-requests
   package:
     name: python3-requests

 - name: Install hook
   template: src=hook.py dest={{ letsencrypt_acme_dns_basedir }}/{{ item.dir }}/deploy_acme_dns.py mode=+x
   with_items: "{{ letsencrypt_acme_dns }}"
